version: 2
formats: all
python:
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
sphinx:
   configuration: docs/conf.py