python helloworld.py "$@"
python oneliners.py "$@"
python ot.py "$@"
python unanimous.py "$@"
python parallelsort.py "$@"
python sort.py "$@"
python indextounitvector.py "$@"
python secretsanta.py "$@"
python id3gini.py "$@"
python lpsolver.py "$@"
python lpsolverfxp.py "$@"
python aes.py "$@" -1
python onewayhashchains.py -k2 "$@"
python elgamal.py -b2 -o3 "$@"
python dsa.py --no-barrier "$@"